sudo: required
services:
        - docker


before_install:
        - docker build -t arajputdocker/docker-react -f Dockerfile.dev .
        

script:
        - docker run arajputdocker/docker-react npm run test -- --coverage 
